edges = [
    ["n1", "n2"],
    ["n1", "n5"],
    ["n1", "n4"],
    ["n2", "n3"],
    ["n3", "n4"],
    ["n4", "n5"],
    ["n6", "n5"],
    ["n6", "n4"],
]

[resources]
n1 = ["r1", "r2", "r3"]
n2 = ["r4", "r5"]
n3 = ["r6"]
n4 = ["r7"]
n5 = ["r8"]
n6 = ["r9"]
