# min_neighbors = 2
# max_neighbors = 4
# (both of these are optional)

edges = [
    ["n1", "n2"],
    ["n1", "n3"],
    ["n2", "n4"],
    ["n2", "n5"],
    ["n5", "n6"],
]

[resources]
n1 = ["r1"]
n2 = ["r2"]
n3 = ["r3"]
n4 = ["r4"]
n5 = ["r5"]
n6 = ["r6"]
